#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip

# install pre-commit hooks to git
pre-commit install

# install in edit mode with testing dependencies
pip install \
    -r \
    requirements.txt
